name: Factions
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.FactionsPlugin
authors: [Olof Larsson, Brett Flannigan, drtshock, CmdrKittens, xt449]
softdepend: [dynamp, LWC, PlaceholderAPI, Sentinel, Vault, WorldGuard]
api-version: '1.16'
commands:
  factions:
    description: Reference command for Factions.
    aliases: [f]
permissions:
  factions.kit.admin:
    description: All faction permissions.
    children:
      factions.kit.mod: true
      factions.config: true
      factions.lock: true
      factions.reload: true
      factions.save: true
      factions.updates: true
      factions.debug: true
  factions.*:
    description: This is just an alias for factions.kit.admin
    children:
      factions.kit.admin: true
  factions.kit.mod:
    description: All faction permissions but configuration and persistance.
    children:
      factions.kit.halfmod: true
      factions.disband.any: true
      factions.setpeaceful: true
      factions.setpermanent: true
      factions.join.any: true
      factions.join.others: true
      factions.admin.any: true
      factions.mod.any: true
  factions.kit.halfmod:
    description: Zones, bypassing, and kicking
    children:
      factions.kit.fullplayer: true
      factions.bypass: true
      factions.kick.any: true
      factions.show.bypassexempt: true
  factions.kit.fullplayer:
    default: true
    description: Can also create new factions and use title colors.
    children:
      factions.kit.halfplayer: true
      factions.create: true
      factions.title.color: true
  factions.kit.halfplayer:
    description: Can do all but create factions.
    children:
      factions.admin: true
      factions.autoclaim: true
      factions.claim: true
      factions.claim.line: true
      factions.claim.radius: true
      factions.coords: true
      factions.deinvite: true
      factions.description: true
      factions.disband: true
      factions.help: true
      factions.invite: true
      factions.join: true
      factions.kick: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.mod: true
      factions.open: true
      factions.relation: true
      factions.show: true
      factions.stuck: true
      factions.tag: true
      factions.title: true
      factions.version: true
      factions.unclaim: true
      factions.unclaimall: true
      factions.scoreboard: true
      factions.showinvites: true
      factions.top: true
      factions.ban: true
      factions.coleader: true
      factions.permissions: true
  factions.admin:
    description: hand over your admin rights
  factions.admin.any:
    description: give or revoke admin status for any player in any faction
  factions.announce:
    description: announce things to the peasants
  factions.autoclaim:
    description: auto-claim land as you walk around
  factions.bypass:
    description: enable admin bypass mode
  factions.claim:
    description: claim land where you are standing
  factions.claim.radius:
    description: claim land in a large radius
  factions.config:
    description: change a conf.json setting
  factions.create:
    description: create a new faction
  factions.deinvite:
    description: remove a pending invitation
  factions.description:
    description: change the faction description
  factions.disband:
    description: disband a faction
  factions.disband.any:
    description: disband another faction
  factions.help:
    description: display a help page
  factions.invite:
    description: invite a player to your faction
  factions.join:
    description: join a faction
  factions.join.any:
    description: join any faction, bypassing invitation process for closed factions
  factions.join.others:
    description: specify another player in the join command, to move them to the specified faction
  factions.kick:
    description: kick a player from the faction
  factions.kick.any:
    description: kick anyone from any faction
  factions.leave:
    description: leave your faction
  factions.list:
    description: see a list of the factions
  factions.lock:
    description: lock all write stuff
  factions.map:
    description: show the territory map, and set optional auto update
  factions.mod:
    description: give or revoke moderator rights
  factions.mod.any:
    description: give or revoke moderator rights for any player in any faction
  factions.open:
    description: switch if invitation is required to join
  factions.setpeaceful:
    description: designate a faction as peaceful
  factions.setpermanent:
    description: designate a faction as permanent
  factions.stuck:
    description: teleports player outside a faction
  factions.relation:
    description: set relation wish to another faction
  factions.reload:
    description: reload data file(s) from disk
  factions.save:
    description: save all data to disk
  factions.show:
    description: show faction information
  factions.show.bypassexempt:
    description: show exempt faction information
  factions.tag:
    description: change the faction tag
  factions.title:
    description: set or remove a players title
  factions.title.color:
    description: set yours or other player's titles to be colored.
  factions.version:
    description: see the version of the plugin
  factions.unclaim:
    description: unclaim the land where you are standing
  factions.unclaimall:
    description: unclaim all of your factions land
  factions.scoreboard:
    description: ability to toggle scoreboards
  factions.showinvites:
    description: show pending invites to your faction
  factions.claim.line:
    description: claim in a line
  factions.top:
    description: sort factions
  factions.autoleavebypass:
    description: Bypass autoleave.
  factions.ban:
    description: Ban players from Factions
  factions.coleader:
    description: Allow use of /f coleader <target>
  factions.updates:
    description: Be informed of available updates to the plugin
  factions.permissions:
    description: Use /f perms
  factions.debug:
    description: Use /f debug
  factions.coords:
    description: Send coordinates to your teammates
  factions.listclaims:
    description: List claims
  factions.listclaims.other:
    description: List claims of other factions
